### PR TITLE
Allow modifier key click

### PR DESCRIPTION
**Pull request by akaleeroy**
Allow user to open image link in new tab or download it by restoring the default functionality to middle-click, Ctrl-click and Alt-click.

### CODE REVIEW

**Comment by thriveweb** [comment]
Thanks 👍

**Comment by thriveweb** [comment]
This will come through with the new release.

**Comment by akaleeroy** [comment]
Not so fast! I just noticed a bug.

On a product page with at least 2 images, click on the second thumbnail, then middle-click on that _second product image_. The _first image_ opens in a new tab instead! 

`.single-product-main-image>a` doesn't update when you click the thumbnail, just the `.single-product-main-image>a>img` src does! It should probably update.

**Comment by akaleeroy** [comment]
Proposed solution: akaleeroy/wooswipe@713a38d5ccb1cb267e83f17a5ece06de46b2665e

**Pull request merged**
